MINIMUM_AMOUNT = 1
MINIMUM_COOKING_TIME = 1

TAG_NAME_MAX_LENGTH = 32
TAG_SLUG_MAX_LENGTH = 32

INGREDIENT_NAME_MAX_LENGTH = 128
INGREDIENT_MEAS_UNIT_MAX_LENGTH = 64

RECIPE_NAME_MAX_LENGTH = 256

SHORTLINK_MAX_LENTH = 50

LEN_SHORT_LINK = 3
