# Generated by Django 3.2.3 on 2024-06-25 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRecipe',
        ),
    ]
