# Generated by Django 3.2.3 on 2024-06-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20240626_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, through='recipes.IngredientInRecipe', to='recipes.Ingredient'),
        ),
    ]
