# Generated by Django 3.2.3 on 2024-06-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20240627_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recip22es', through='recipes.IngredientInRecipe', to='recipes.Ingredient'),
        ),
    ]
